services:
  mysql:
    image: mysql:8.4.2
    
    container_name: template-spring-boot-db
    
    restart: unless-stopped
    
    ports:
      - "${DB_EXPOSED_PORT:-2203}:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
      MYSQL_USER: template_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-template_user_pass}
    
    volumes:
      - template-spring-boot-db:/var/lib/mysql
    
    command:
      - "--mysql-native-password=ON"
      - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"      
    
    networks:
      - template-spring-boot-network

  application:
    image: template-spring-boot-application
    
    container_name: template-spring-boot-application
    
    restart: unless-stopped
    
    stdin_open: true
    
    tty: true
    
    build:
      dockerfile: Dockerfile.local
      context: ./docker
    
    ports:
      - "${TEMPLATE_SPRING_BOOT_EXPOSED_PORT:-4040}:8080"
    
    working_dir: /opt/app
    
    volumes:
      - ./:/opt/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    
    command: bash -c "chmod +x ./docker/scripts/run_local.sh && ./docker/scripts/run_local.sh"
    
    networks:
      - template-spring-boot-network


networks:
  template-spring-boot-network:
    driver: bridge

volumes:
  template-spring-boot-db: